name: Tests
on:
    push:
        branches: [main, use-deno]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
            - run: deno lint

    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: denoland/setup-deno@v2
            - run: |
                  deno install
                  deno task example:build
                  npx playwright install --with-deps
                  npx playwright test
